const BASE_URL = __ENV.BASE_URL || 'http://localhost:5000';
const API_PREFIX = '/api';

export const CONFIG = {
  baseUrl: `${BASE_URL}${API_PREFIX}`,
  endpoints: {
    auth: {
      login: '/auth/login',
      register: '/auth/register',
      refresh: '/auth/refresh',
      logout: '/auth/logout',
      csrfToken: '/auth/csrf-token',
      resetPassword: '/auth/reset-password',
      forgotPassword: '/auth/forgot-password',
      verifyEmail: '/auth/verify-email',
    },
    interns: {
      list: '/interns',
      create: '/interns',
      get: (id) => `/interns/${id}`,
      update: (id) => `/interns/${id}`,
      delete: (id) => `/interns/${id}`,
      search: '/interns/search',
      bulkCreate: '/interns/bulk',
      exportCSV: '/interns/export/csv',
      stats: '/interns/stats',
    },
    mentors: {
      list: '/mentors',
      assign: '/mentors/assign',
      unassign: '/mentors/unassign',
      myInterns: '/mentors/my-interns',
      get: (id) => `/mentors/${id}`,
    },
    attendance: {
      mark: '/attendance',
      bulkMark: '/attendance/bulk',
      history: '/attendance/history',
      stats: '/attendance/stats',
      export: '/attendance/export',
      today: '/attendance/today',
      report: '/attendance/report',
    },
    progress: {
      submit: '/progress',
      list: '/progress',
      get: (id) => `/progress/${id}`,
      review: (id) => `/progress/${id}/review`,
      stats: '/progress/stats',
      weekly: '/progress/weekly',
    },
    dashboard: {
      stats: '/dashboard/stats',
      charts: '/dashboard/charts',
      summary: '/dashboard/summary',
      recentActivity: '/dashboard/recent-activity',
      notifications: '/dashboard/notifications',
      analytics: '/dashboard/analytics',
      overview: '/dashboard/overview',
    },
    reports: {
      generate: '/reports/generate',
      list: '/reports',
      get: (id) => `/reports/${id}`,
      download: (id) => `/reports/${id}/download`,
      schedule: '/reports/schedule',
      templates: '/reports/templates',
    },
    exports: {
      csv: '/exports/csv',
      pdf: '/exports/pdf',
      excel: '/exports/excel',
      status: (id) => `/exports/${id}/status`,
      download: (id) => `/exports/${id}/download`,
    },
    notifications: {
      list: '/notifications',
      markRead: (id) => `/notifications/${id}/read`,
      markAllRead: '/notifications/read-all',
      count: '/notifications/count',
      settings: '/notifications/settings',
      subscribe: '/notifications/subscribe',
    },
    sessions: {
      list: '/sessions',
      revoke: (id) => `/sessions/${id}/revoke`,
      revokeAll: '/me/revoke-all',
      current: '/sessions/current',
    },
    users: {
      profile: '/users/profile',
      updateProfile: '/users/profile',
      changePassword: '/users/change-password',
      updatePreferences: '/users/preferences',
    },
    admin: {
      dashboard: '/admin/dashboard',
      users: '/admin/users',
      revokeUser: (id) => `/admin/revoke-user/${id}`,
      systemLogs: '/admin/system-logs',
      metrics: '/admin/metrics',
      config: '/admin/config',
    },
  },
  thresholds: {
    baseline: {
      http_req_duration: ['p(95)<300', 'p(99)<500'],
      http_req_failed: ['rate<0.01'],
    },
    normal: {
      http_req_duration: ['p(95)<500', 'p(99)<1000'],
      http_req_failed: ['rate<0.02'],
    },
    peak: {
      http_req_duration: ['p(95)<1000', 'p(99)<2000'],
      http_req_failed: ['rate<0.05'],
    },
    stress: {
      http_req_duration: ['p(95)<2000', 'p(99)<4000'],
      http_req_failed: ['rate<0.10'],
    },
  },
  stages: {
    baseline: [
      { duration: '2m', target: 10 },
      { duration: '5m', target: 10 },
      { duration: '2m', target: 0 },
    ],
    normal: [
      { duration: '5m', target: 50 },
      { duration: '10m', target: 50 },
      { duration: '10m', target: 100 },
      { duration: '10m', target: 100 },
      { duration: '5m', target: 0 },
    ],
    peak: [
      { duration: '5m', target: 100 },
      { duration: '15m', target: 500 },
      { duration: '15m', target: 1000 },
      { duration: '10m', target: 2000 },
      { duration: '10m', target: 2000 },
      { duration: '5m', target: 0 },
    ],
    stress: [
      { duration: '2m', target: 50 },
      { duration: '3m', target: 100 },
      { duration: '3m', target: 500 },
      { duration: '3m', target: 1000 },
      { duration: '3m', target: 2000 },
      { duration: '3m', target: 3000 },
      { duration: '2m', target: 5000 },
      { duration: '2m', target: 5000 },
      { duration: '3m', target: 0 },
    ],
    spike: [
      { duration: '2m', target: 50 },
      { duration: '30s', target: 500 },
      { duration: '5m', target: 500 },
      { duration: '30s', target: 50 },
      { duration: '3m', target: 50 },
    ],
    endurance: [
      { duration: '10m', target: 50 },
      { duration: '30m', target: 100 },
      { duration: '60m', target: 100 },
      { duration: '30m', target: 150 },
      { duration: '60m', target: 150 },
      { duration: '10m', target: 0 },
    ],
  },
};

export function getRandomEmail() {
  const domains = ['test.com', 'example.com', 'loadtest.io', 'perf.com'];
  const domain = domains[Math.floor(Math.random() * domains.length)];
  return `load_${Date.now()}_${Math.random().toString(36).substring(2, 8)}@${domain}`;
}

export function getRandomName() {
  const firstNames = [
    'Aarav',
    'Vivaan',
    'Aditya',
    'Vihaan',
    'Arjun',
    'Sai',
    'Reyansh',
    'Ayaan',
    'Krishna',
    'Ishaan',
    'Ananya',
    'Priya',
    'Neha',
    'Riya',
    'Meera',
    'Kavya',
    'Shreya',
    'Diya',
    'Aditi',
    'Sara',
    'Rahul',
    'Amit',
    'Vikram',
    'Suresh',
    'Deepak',
    'Manish',
    'Rajesh',
    'Sanjay',
    'Anil',
    'Vijay',
    'Pooja',
    'Sunita',
    'Lakshmi',
    'Geeta',
    'Rekha',
    'Anita',
    'Kavita',
    'Swati',
    'Divya',
    'Shweta',
    'James',
    'Maria',
    'Robert',
    'Linda',
    'Michael',
    'Jennifer',
    'David',
    'Susan',
    'Daniel',
    'Sarah',
    'Thomas',
    'Jessica',
    'Kevin',
    'Ashley',
    'Brandon',
    'Amanda',
    'Jason',
    'Nicole',
    'Ryan',
    'Stephanie',
    'Eric',
    'Megan',
    'Brian',
    'Lauren',
  ];
  const lastNames = [
    'Sharma',
    'Verma',
    'Patel',
    'Kumar',
    'Singh',
    'Reddy',
    'Gupta',
    'Joshi',
    'Nair',
    'Menon',
    'Das',
    'Bose',
    'Rao',
    'Prasad',
    'Agarwal',
    'Mehta',
    'Smith',
    'Johnson',
    'Williams',
    'Brown',
    'Jones',
    'Garcia',
    'Miller',
    'Davis',
    'Wilson',
    'Moore',
    'Taylor',
    'Anderson',
    'Thomas',
    'Jackson',
    'White',
    'Harris',
  ];
  const first = firstNames[Math.floor(Math.random() * firstNames.length)];
  const last = lastNames[Math.floor(Math.random() * lastNames.length)];
  return `${first} ${last}`;
}

export function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

export function randomArrayElement(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}
