import React from 'react';
import { useQuery } from '@tanstack/react-query';
import api from '../lib/axios';
import { QUERY_KEYS } from '../constants/queryKeys';
import { Card, Spinner, ApiErrorState, Badge } from './ui';
import { Award, TrendingUp, CheckCircle, Zap, Target } from 'lucide-react';

export default function AssessmentSection({ userId }) {
  const {
    data: assessment,
    isLoading,
    isError,
    error,
    refetch,
  } = useQuery({
    queryKey: [...QUERY_KEYS.ASSESSMENT, userId],
    queryFn: () =>
      api.get(`/assessments/user/${userId}`).then((res) => res.data),
    retry: 1,
    staleTime: 5 * 60 * 1000,
    enabled: !!userId,
  });

  if (isLoading) {
    return (
      <Card className="p-8 flex items-center justify-center border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900">
        <Spinner label="Analysing AI assessment data..." />
      </Card>
    );
  }

  if (isError) {
    if (error?.response?.status === 404) {
      return (
        <Card className="p-8 border border-slate-200 dark:border-slate-700 bg-gradient-to-br from-white via-slate-50 to-indigo-50/40 dark:from-slate-900 dark:via-slate-900 dark:to-slate-800/60 shadow-[0_14px_35px_rgba(15,23,42,0.04)] text-center">
          <div className="w-16 h-16 mx-auto rounded-3xl bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 dark:text-indigo-300 border border-indigo-100 dark:border-indigo-900/60 flex items-center justify-center text-3xl shadow-sm mb-4 animate-pulse">
            🤖
          </div>
          <h3 className="font-extrabold text-xl text-slate-900 dark:text-white">
            No AI Assessment Yet
          </h3>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-2 max-w-md mx-auto">
            Your workforce readiness and skills assessments will appear here
            once generated by supervisors or automated sync.
          </p>
        </Card>
      );
    }

    return (
      <ApiErrorState
        error={error}
        title="Failed to load AI Assessment"
        fallback="An error occurred while loading your AI assessment score."
        onRetry={refetch}
      />
    );
  }

  if (!assessment) return null;

  const scorePct = Number(assessment.score) || 0;
  const strengths = Array.isArray(assessment.key_strengths)
    ? assessment.key_strengths
    : [];
  const improvements = Array.isArray(assessment.improvement_areas)
    ? assessment.improvement_areas
    : [];
  const nextActions = Array.isArray(assessment.next_actions)
    ? assessment.next_actions
    : [];

  let scoreColorClass = 'text-indigo-600 dark:text-indigo-400';
  let scoreBgClass =
    'bg-indigo-50 dark:bg-indigo-950/40 border-indigo-100 dark:border-indigo-900/60';

  if (scorePct >= 80) {
    scoreColorClass = 'text-emerald-600 dark:text-emerald-400';
    scoreBgClass =
      'bg-emerald-50 dark:bg-emerald-950/30 border-emerald-100 dark:border-emerald-900/40';
  } else if (scorePct >= 60) {
    scoreColorClass = 'text-amber-600 dark:text-amber-400';
    scoreBgClass =
      'bg-amber-50 dark:bg-amber-950/30 border-amber-100 dark:border-amber-900/40';
  } else {
    scoreColorClass = 'text-rose-600 dark:text-rose-400';
    scoreBgClass =
      'bg-rose-50 dark:bg-rose-950/30 border-rose-100 dark:border-rose-900/40';
  }

  return (
    <Card className="p-6 md:p-8 border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 shadow-[0_14px_35px_rgba(15,23,42,0.06)] dark:shadow-none animate-fade-in-up">
      <div className="flex flex-col md:flex-row md:items-center justify-between pb-5 border-b border-slate-200 dark:border-slate-700 gap-4 mb-6">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-indigo-50 dark:bg-indigo-950/40 border border-indigo-100 dark:border-indigo-900/60 text-indigo-600 dark:text-indigo-300 flex items-center justify-center shadow-sm">
            <Award className="w-6 h-6" />
          </div>
          <div>
            <h3 className="font-extrabold text-xl text-slate-900 dark:text-white">
              AI Workforce Assessment
            </h3>
            <p className="text-sm text-slate-500 dark:text-slate-400 mt-0.5">
              Comprehensive evaluation of core engineering and workspace
              capabilities
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-xs font-bold text-slate-500 uppercase tracking-widest bg-slate-100 dark:bg-slate-800 px-3 py-1 rounded-full">
            {assessment.status}
          </span>
          {assessment.completed_at && (
            <span className="text-xs text-slate-400">
              {new Date(assessment.completed_at).toLocaleDateString()}
            </span>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 mb-6">
        <div className="lg:col-span-4 flex flex-col items-center justify-center p-6 rounded-3xl border border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/50">
          <div className="relative flex items-center justify-center w-32 h-32">
            <svg
              className="w-full h-full transform -rotate-90"
              aria-label={`Assessment score ${scorePct}%`}
            >
              <circle
                cx="64"
                cy="64"
                r="56"
                className="stroke-slate-200 dark:stroke-slate-800"
                strokeWidth="10"
                fill="transparent"
              />
              <circle
                cx="64"
                cy="64"
                r="56"
                className="stroke-indigo-600 dark:stroke-indigo-400"
                strokeWidth="10"
                fill="transparent"
                strokeDasharray={351.8}
                strokeDashoffset={351.8 - (351.8 * scorePct) / 100}
                strokeLinecap="round"
              />
            </svg>
            <div className="absolute flex flex-col items-center justify-center">
              <span className="text-3xl font-extrabold text-slate-950 dark:text-white">
                {scorePct}%
              </span>
              <span className="text-[10px] text-slate-500 font-bold uppercase tracking-wider">
                Score
              </span>
            </div>
          </div>
          <div
            className={`mt-4 px-4 py-1.5 rounded-full border text-sm font-extrabold shadow-sm ${scoreBgClass} ${scoreColorClass}`}
          >
            Category: {assessment.category}
          </div>
        </div>

        <div className="lg:col-span-8 flex flex-col justify-between">
          <div className="space-y-4">
            <div>
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-1">
                AI Performance Feedback
              </h4>
              <p className="text-slate-700 dark:text-slate-300 text-sm leading-relaxed whitespace-pre-line italic">
                "{assessment.feedback || 'No feedback provided.'}"
              </p>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 rounded-2xl border border-slate-100 dark:border-slate-800/80 bg-slate-50/30 dark:bg-slate-900/30">
                <span className="block text-xs font-bold text-slate-400 uppercase tracking-wide">
                  Scope Covered
                </span>
                <span className="text-lg font-extrabold text-slate-900 dark:text-white mt-1 block">
                  {assessment.questions_count || 0} Dimensions
                </span>
              </div>
              <div className="p-4 rounded-2xl border border-slate-100 dark:border-slate-800/80 bg-slate-50/30 dark:bg-slate-900/30">
                <span className="block text-xs font-bold text-slate-400 uppercase tracking-wide">
                  Status
                </span>
                <span className="text-lg font-extrabold text-emerald-600 dark:text-emerald-400 mt-1 flex items-center gap-1.5">
                  <CheckCircle className="w-5 h-5 shrink-0" /> Verified
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
        <div className="p-5 md:p-6 rounded-3xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900">
          <h4 className="text-sm font-extrabold text-slate-900 dark:text-white mb-4 flex items-center gap-2">
            <Zap className="w-5 h-5 text-emerald-500" />
            Key Strengths
          </h4>
          {strengths.length === 0 ? (
            <p className="text-sm text-slate-500">No strengths logged yet.</p>
          ) : (
            <div className="flex flex-wrap gap-2">
              {strengths.map((item, idx) => (
                <Badge key={idx} color="green">
                  {item}
                </Badge>
              ))}
            </div>
          )}
        </div>

        <div className="p-5 md:p-6 rounded-3xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900">
          <h4 className="text-sm font-extrabold text-slate-900 dark:text-white mb-4 flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-amber-500" />
            Areas of Improvement
          </h4>
          {improvements.length === 0 ? (
            <p className="text-sm text-slate-500">
              No improvement areas logged yet.
            </p>
          ) : (
            <div className="flex flex-wrap gap-2">
              {improvements.map((item, idx) => (
                <Badge key={idx} color="yellow">
                  {item}
                </Badge>
              ))}
            </div>
          )}
        </div>
      </div>

      {nextActions.length > 0 && (
        <div className="p-5 md:p-6 rounded-3xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900">
          <h4 className="text-sm font-extrabold text-slate-900 dark:text-white mb-4 flex items-center gap-2">
            <Target className="w-5 h-5 text-indigo-500" />
            Recommended Next Actions
          </h4>
          <div className="space-y-3">
            {nextActions.map((action, idx) => (
              <div
                key={idx}
                className="flex items-start gap-3 p-3 rounded-2xl bg-indigo-50/30 dark:bg-indigo-950/10 border border-indigo-500/10"
              >
                <div className="w-6 h-6 rounded-lg bg-indigo-600 text-white flex items-center justify-center text-xs font-bold shrink-0 mt-0.5 shadow-sm">
                  {idx + 1}
                </div>
                <div className="text-sm text-slate-700 dark:text-slate-300 font-medium leading-relaxed">
                  {action}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </Card>
  );
}
